### ISSUE TITLE
Use your own TO-DO as github issue

### ISSUE THREAD

**Issue by shakaran** [sabueso/zimbra-letsencrypt-renewal#2]
Taken harcoded in code, you can use just "todo" list in github:

- [ ] Improve echo messages with colors
- [ ] Fill all actions with messages
- [ ] Make control structures to know if last actions fails
- [ ] Test version of zimbra and execute with or without zimbra user zmcertmgr
